test_trained_models.py
Previous fixed threshold caused CI test errors
=> Change CI test error

.github/workflows/CI.yml
Another attempt at working a cache, removing the virtual environment, and pointing the cache to the entire python environment. Also explicitly sets which requirements files matter for the cache
=> Cache entire python env

examples/ci.json, models/Base.py, models/GATStack.py, models/GINStack.py, models/MFCStack.py, models/PNNStack.py, models/__init__.py, test_training.py, utils/models_setup.py, utils/utils.py
Combine functionality shared across models. 
~~@pzhanggit I wasn't exactly sure how to separate the graph layer initialization from the multi-head init, but I think this moves in the direction we discussed. Kind of the same thing, should we have forward propagation functions with and without multi-heads?~~
With this approach, all models now have multi-heading which is tested in the CI (running without error, no specific accuracy checks yet)
=> Base model

.github/workflows/CI.yml
Save time for unformatted code
=> Format before running tests

data_utils/raw_dataset_loader.py, data_utils/serialized_dataset_loader.py, examples/configuration.json, run_config_input.py, utils/utils.py
1. added a flag to output predictions with unit
2. saved minimum and maximum values used in normalization to data files *.pkl
=> Optional output normalization

data_utils/raw_dataset_loader.py, data_utils/serialized_dataset_loader.py, examples/configuration.json, run_config_input.py, utils/utils.py
=> Revert "Optional output normalization"

data_utils/raw_dataset_loader.py, data_utils/serialized_dataset_loader.py, examples/configuration.json, run_config_input.py, utils/utils.py
Re-add from #37 and undo revert #38, adds `denormalize_output` for terminal input
=> Re-add Optional output normalization

utils/random_graph_data.py
number of samples brought back to 1000 to avoid occasional test failure (loss function not dropping below threshold)
=> Increase test node count

test_random_graphs.py, utils/utils.py
Fixup for running without MPI. Tests now run with and without MPI
=> added check if dist is initialized

data_utils/raw_dataset_loader.py, run_config_input.py
Missed a few places in the previous PR #53 of general code improvement:
improve data normalization and add restart
=> General code improvement part 2

examples/ci.json, examples/configuration.json, models/Base.py, models/GATStack.py, models/GINStack.py, models/MFCStack.py, models/PNNStack.py, run_config_input.py, test_trained_model.py, utils/models_setup.py
1. Separate NN structures for graph and node level predictions
2. Make NN structures for graph and node configurable
3. Tested for node level prediction locally, though not in CI test yet
=> General improvement part3: separate NN structure for graph and node level output

examples/configuration.json
=> fixup a bug in configuration.json

CONTRIBUTING.md, README.md
Try to remove out of date information and add contributing instructions
Part of #64
=> Update readme and add contributing

models/GATStack.py, models/GINStack.py, models/MFCStack.py, models/PNNStack.py
~~Double check GAT and improve to GATv2~~ (separate PR)
=> Model implementation improvement

data_utils/raw_dataset_loader.py, test_graphs.py
Also modifies unit test to use different error threshold per model
=> Fix normalization indexing bug

data_utils/raw_dataset_loader.py
Guard against accidentally included file in CuAu dataset
Related to #79
=> CuAu dataset bugfix

test_graphs.py, utils/deterministic_graph_data.py
Node features in unit test now include information from neighboring nodes
=> aggregating nodal features in unit tests

README.md, models/PNAStack.py, models/__init__.py, models/models_setup.py, run_config_input.py, test_graphs.py, test_trained_model.py, utils/__init__.py, utils/models_setup.py
- Move model generation to models
- Rename PNA
- Error for unknown model type
=> Model cleanup

run_config_input.py, test_trained_model.py, utils/utils.py
Fixes #58 (@allaffa if you use these keywords it will automatically close related issues on merge)
=> Use dist.is_init and check torch.is_nccl_available

README.md, data_utils/helper_functions.py, data_utils/serialized_dataset_loader.py, data_utils/tester.py, examples/ci.json, examples/ci_multihead.json, examples/configuration.json, run_config_input.py, test_trained_model.py, utils/__init__.py, utils/print_utils.py, utils/utils.py
=> Verbosity distributed print

data_utils/helper_functions.py, data_utils/serialized_dataset_loader.py, models/models_setup.py, run_config_input.py, test_trained_model.py, utils/__init__.py, utils/print_utils.py, utils/utils.py
Fixup #97 for use of CPU vs GPU
=> fixup: verbosity distributed print

data_utils/raw_dataset_loader.py, examples/ci.json, examples/ci_multihead.json, examples/configuration.json, test_graphs.py, utils/utils.py
Also rewrites `RawDataLoader` and no longer requires explicit match to known datasets
@pzhanggit you can close issues automatically with this:
Fixes #34
=> add capability for explicit train/test/validate paths
